repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: []
        args: [
            "--count",
            "--select=E9,F63,F7,F82,F824",
            "--show-source",
            "--statistics",
            "--max-line-length=127",
            "--max-complexity=10"
        ]